# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24a929574589de22ab8e061d807c2d5807c11dc6377f0ab71f50d9eb12573b643268b1769e5029561a306041dd1381976cdf05f1efadb77fd1d9ba1fc816edd6

test:
  secret_key_base: 252af19ee02b63912bc19c22942173290779bd9a98a2341fb43aff455b10b66795c1c8577c0e88daa76770742e6f8cd9dc5cc75a3680a8f72ed740e1f1e88c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
